services:
  server:
    image: registry.greendelta.com/hub/collaboration-server:latest
    container_name: lcacollab
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - SERVER_URL
      - MYSQL_URL=lcacollab-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - SEARCH_ENABLED=true
      - SEARCH_SCHEMA=http
      - SEARCH_HOST=lcacollab-search
      - SEARCH_PORT=9200
    volumes:
      - server:/opt/collab

  db:
    image: mysql:8.1
    container_name: lcacollab-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db:/var/lib/mysql

  search:
    image: opensearchproject/opensearch:2.17.1
    container_name: lcacollab-search
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD
    ports:
      - 9200:9200
      - 9600:9600

volumes:
  db:
    name: lcacollab-db
  server:
    name: lcacollab-server
