version: '3.8'

services:
  server:
    image: lca-collaboration-server
    container_name: collaboration-server
    build: .
    command: bash -c "java -jar /opt/install/installer.jar -p /opt/install/installer.config ; catalina.sh run ;"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - server-data:/opt/collab
      - ./application.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties
    networks:
      - collaboration
  db:
    image: mysql:8.1
    container_name: collaboration-server-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=collaboration-server
      - MYSQL_USER=collaboration-server
      - MYSQL_PASSWORD=collaboration-server
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - collaboration
volumes:
  db-data:
  server-data:
networks:
  collaboration:
