services:

  server:
    image: collaboration-server
    container_name: collaboration-server
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - server-data:/opt/collab

  db:
    image: mysql:8.1
    container_name: collaboration-server-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql

  search:
    image: opensearchproject/opensearch:2.17.1
    container_name: collaboration-server-search
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD
    ports:
      - 9200:9200
      - 9600:9600

volumes:
  db-data:
  server-data:
