services:
  server:
    image: registry.greendelta.com/hub/collaboration-server:latest
    container_name: lcacollab
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      - SERVER_URL
      - DATABASE_URL=jdbc:mariadb://lcacollab-db:3306/${MARIADB_DATABASE}
      - DATABASE_USER=${MARIADB_USER}
      - DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - SEARCH_ENABLED=true
      - SEARCH_SCHEMA=http
      - SEARCH_HOST=lcacollab-search
      - SEARCH_PORT=9200
    volumes:
      - server:/opt/collab

  db:
    image: mariadb:12.3
    container_name: lcacollab-db
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - db:/var/lib/mysql

  search:
    image: opensearchproject/opensearch:3.8.0
    container_name: lcacollab-search
    restart: unless-stopped
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - discovery.type=single-node
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - search:/usr/share/opensearch/data

volumes:
  db:
    name: lcacollab-db
  server:
    name: lcacollab-server
  search:
    name: lcacollab-search

