services:
  server:
    image: collaboration-server
    container_name: collaboration-server
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - server-data:/opt/collab
      - type: tmpfs
        target: /usr/local/tomcat/logs
      - type: tmpfs
        target: /root/.config
    read_only: true
volumes:
  server-data:
