services:
  server:
    image: lcacollab
    container_name: lcacollab
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL
      - MYSQL_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - server:/opt/collab
      - type: tmpfs
        target: /usr/local/tomcat/logs
      - type: tmpfs
        target: /home/collab/.config
    read_only: true
volumes:
  server:
    name: lcacollab-server
