version: '3.8'

services:
  cs-db:
    image: cs-db
    container_name: cs-db
    build: .
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=cs-db
      - MYSQL_USER=cs-db
      - MYSQL_PASSWORD=cs-db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10