---
- name: Single node ElasticSearch cluster
  hosts: all
  become: true
  vars:
    elasticsearch_heap_size_min: 2g
    elasticsearch_network_host: 0.0.0.0
    elasticsearch_extra_options: |
      discovery.type: single-node
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.elasticsearch
